//  Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.
:page-tags: ['REST', 'Getting Started']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
//:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:common-includes: ../guides-common
:seo-title: Test
:seo-description: description
= Getting started with Open Liberty Java app server

Learn how to run and update an app on the Open Liberty Java app server using Maven.

== What you'll learn

You will learn how to run a simple REST service that exposes the JVM's system properties on an Open Liberty server using Maven. Maven is an efficient way to start developing apps or microservices for Open Liberty. Using Maven, you will create a simple microservice that collects basic system properties from our laptop and displays them on an endpoint that you can access in your web browser. The microservice uses JAX-RS and JSON-P to provide the endpoint for accessing the system properties. After running this simple microservice on an Open Liberty server, you will create another class to add a second RESTful endpoint that collects metrics about the running microservice.


//include::{common-includes}/gitclone.adoc[]

== Cloning and running the app on an Open Liberty server

In a terminal, run the following commands to clone a simple app:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-{projectid}.git
cd guide-{projectid}
----

The `start` directory contains the starting project that you can use to begin. The `finish` directory contains the finished project, which is what you will build.

// start directory needs to contain the same as the finish but without the class modification in the next section.

Change into the `start` directory:

----
cd start
----

Try compiling and running the app to see what it does:

----
mvn install liberty:run-server
----

//Currently the sample is not working like this https://github.com/OpenLiberty/sample-getting-started/issues/16

The `mvn install` part of the command (Maven goal) compiles the application and downloads the latest stable release of the Open Liberty runtime to a local cache. The `liberty:run-server` goal creates and starts a server called `defaultServer` and deploys the application to the server.

To see what the app does, visit the following URL in a web browser:

[source,role="no_copy"]
----
http://localhost:9080/system/properties
----

The app gets the system properties for your laptop and displays them on a simple webpage at that URL endpoint; for example like this:

[source,role="no_copy"]
----
{"java.vendor":"Oracle Corporation","default.https.port":"9443","sun.java.launcher":"SUN_STANDARD","sun.management.compiler":"HotSpot 64-Bit Tiered Compilers","shared.resource.dir":"/Users/laura/github/lauracowen/sample-getting-started/finish/target/liberty/wlp/usr/shared/resources/","os.name":"Mac OS X","sun.boot.class.path":"/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk
...
----

== Updating the app code without restarting the server

The application is configured as a 'loose application'. This means that Open Liberty runs the application from the `target/classes` directory, which is where the compiler puts the classes before compiling them into a WAR file. Liberty monitors the `classes` directory of the running application. Whenever a class is updated, Liberty automatically updates the application. You don't need to repeatedly restart the server or manually redeploy your app to see the effects of every update you make to your code. You can configure your IDE (such as VSCode with xxxx extension or Eclipse with Open Liberty Tools) to trigger a Maven build when you save a file.

(Using VSCode? Make sure you've installed the Java Extensions and you open the `start` folder directly in the VSCode workspace so that the `pom.xml` is in the 'root' of the workspace project.)

Without 'loose application' enabled for an app, Maven would compile the app and put WAR file in the server's `apps` directory (`target/liberty/usr/servers/defaultServer/apps`) so that Open Liberty can load the application. When 'loose application' is enabled, Maven places a `.war.xml` file (for this app it's called `rest.war.xml`) in the `apps` directory instead of the compiled WAR file. The `rest.war.xml` file directs Open Liberty to find the application classes in the `target/classes` directory instead of the `apps` directory.

Take a look at the `pom.xml` for the sample app. The `<looseApplication>` setting is set to `true` so that Open Liberty checks for updated classes in the `target/classes` directory.

With the application still running, try making a minor edit to the `SystemResource.java` class. Add a comment somewhere in the class then save the file. [LC: Could so with something better than this but adding the runtime exception at this point is a bit negative and a bit of a tangent.]

Check the console output in the terminal where you ran the `mvn` command. The output updates each time you save updates to a file to show that the server has detected the changes and updated the running application:

----
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://lauras-mbp.hursley.uk.ibm.com:9080/
[INFO] [AUDIT   ] CWWKZ0009I: The application io.openliberty.sample.getting.started has stopped successfully.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://lauras-mbp.hursley.uk.ibm.com:9080/
[INFO] [AUDIT   ] CWWKZ0003I: The application io.openliberty.sample.getting.started updated in 0.136 seconds.
---- 


== Open Liberty logs

You can find the logs for the application's Open Liberty server in the `target/liberty/wlp/usr/servers/SampleAppServer/logs` directory, which is created automatically when the server first starts. There should currently be `console.log` and `messages.log` files in the directory which contain the console output of the running app so far.

Now, force a RuntimeException by editing the `SystemResource.java` class: Insert the following `if` statement at the very start of the `getProperties()` method:

[source,java,indent=0]
----
if (System.getProperties() != null) {
   throw new RuntimeException("My forced exception");
	}
----

The app is reloaded when you save the change. Vist the URL again:

[source,role="no_copy"]
----
http://localhost:9080/system/properties
----

This time, instead of returning the system properties, the app throws a RuntimeException called `My forced exception`, like this:

[source,role="no_copy"]
----
Exception thrown by application class 'io.openliberty.sample.system.SystemResource.getProperties:42'
java.lang.RuntimeException: My forced exception
at io.openliberty.sample.system.SystemResource.getProperties(SystemResource.java:42)
at io.openliberty.sample.system.SystemResource$Proxy$_$$_WeldSubclass.getProperties$$super(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
----

In the `logs` directory, you should now see addition `ffdc` and `state` directories containing the FFDC (First Failure Data Capture - link to more info?) and the ??? logs about the RuntimeException.

Remove the RuntimeException statement again and save the file and the app will return the system properties again. All without needing to restart the server.

Stop the server by pressing CTRL + C.

== Starting and stopping the server in the background

In the previous sections, you started and stopped the server in the foreground using Maven. You can also start and stop the server in the background using Maven:

[source,role="no_copy"]
----
liberty:start-server
liberty:stop-server
----

== Packaging and deploying the app to another server

Although it's useful to be able to easily package and run the application in a development environment, at some point you'll need to deploy the app to a server in a test or production environment. You can use Maven to package the application then move the packaged application to the `apps` or `dropins` directory of the Open Liberty server in the test or production environment.

Package your app:

[source,role="no_copy"]
----
mvn package
----

Maven creates a package called `LibertyProject.zip` in the `target` directory:

[source,role="no_copy"]
----
...
[INFO] Packaging server sampleAppServer.
[INFO] Server sampleAppServer package complete in /Users/laura/github/lauracowen/sample-getting-started/finish/target/LibertyProject.zip.
...
----

Download an Open Liberty runtime from https://openliberty.io/downloads/. Extract the downloaded ZIP file to a location on your harddrive. You have now installed the Open Liberty runtime.

The `LibertyProject.zip` package contains your compiled app along with a server in a `wlp` directory. Extract the package over the Open Liberty installation (so that the `usr` directory containing your packaged app drops into the `wlp` directory of the Open Liberty runtime. The packaged `...war` file is in the `usr/servers/sampleAppServer/apps`.

To start the server, in a terminal, navigate to the `wlp/bin` directory of the Open Liberty installation and start the server:

[source]
----
cd wlp/bin
./server start sampleAppServer
----

When the server has started, visit the app URL again:

[source,role="no_copy"]
----
http://localhost:9080/system/properties
----

[LC: For me, this doesn't quite work - I get context not found problem and I'm not sure why.]

To stop the server:

[source]
----
./server stop sampleAppServer
----


MINIFY??

ANYTHING ELSE WE SHOULD INTRODUCE ABOUT OPEN LIBERTY?


== Great work! You're done!

You've learnt the basics of deploying and updating an app on an Open Liberty server.

include::{common-includes}/finish.adoc[]
